FROM phpdockerio/php73-fpm:latest
USER root

RUN mkdir ~/application

RUN apt-get update && apt-get install -y wget && apt-get install -y nginx

ENV DOCKERIZE_VERSION v0.6.1

RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

WORKDIR "/application"

COPY ./app .

COPY ./php-fpm/php-ini-overrides.ini /etc/php/7.3/fpm/conf.d/99-overrides.ini

# Fix debconf warnings upon build
ARG DEBIAN_FRONTEND=noninteractive

# Install selected extensions and other stuff
RUN apt-get update \
    && apt-get -y --no-install-recommends install  php7.3-mysql php-redis php7.3-bcmath php7.3-gmp \
    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
# Add user for laravel application

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -

RUN apt-get install nodejs -y

#Instalando composer
RUN apt-get install php-cli php-mbstring php-xml git unzip -y

#Setando php72 como padrão
RUN update-alternatives --set php /usr/bin/php7.3