version: "3.1"
services:
##################################################
#                   REDIS                        #
##################################################
    redis:
      image: redis:alpine
      container_name: redis
      restart: always
      ports:
        - "6379:6379"
      networks:
        - app-network
##################################################
#                 PHPMYADMIN                     #
##################################################
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: phpmyadmin
      environment:
        - PMA_ARBITRARY=1
      ports:
        - "8082:80"
      networks:
        - app-network

##################################################
#                 MYSQL                          #
##################################################
    mysql:
      image: mysql:5.7
      container_name: mysql
      working_dir: /var/lib/mysql
      restart: always
      volumes:
        - ./.docker/dbdata:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=acl_bd
        - MYSQL_USER=acl_user
        - MYSQL_PASSWORD=secret
      ports:
        - "3306:3306"
      networks:
        - app-network
##################################################
#                 NGINX                          #
##################################################
    nginx:
      build:
        context: ./
        dockerfile: Dockerfile-nginx
      container_name: nginx
      working_dir: /application
      restart: always
      volumes:
        - ./app:/application
      ports:
        - "8081:80"
      networks:
        - app-network
##################################################
#                 PHP-FPM                        #
##################################################
    php-fpm:
      build:
        context: ./
        dockerfile: Dockerfile-php-fpm
      container_name: php-fpm
      working_dir: /application
      volumes:
        - ./app:/application
      restart: always
      networks:
        - app-network
      environment:
        - APP_DEBUG=true
        - CACHE_DRIVER=redis
        - SESSION_DRIVER=redis
##################################################
#              REDES DOCKER                      #
##################################################
networks:
  app-network:
